### ISSUE TITLE
Does not compile on perl 5.44

### ISSUE THREAD

**Issue by mauke** [jeffreykegler/Marpa--R2#298]
See https://www.cpantesters.org/cpan/report/f00f68cc-721a-11f1-8685-c5e7b9a02d72.

```
...
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h: In function ‘Perl_cx_poploop’:
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4352:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 4352 |         PADOFFSET how_many = iterop->op_targ;
      |         ^~~~~~~~~
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4357:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
 4357 |         for (SV **svp = cx->blk_loop.itervar_u.svp + 1; how_many; svp++, how_many--) {
      |         ^~~
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4357:9: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4370:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 4370 |         MAGIC *mg = SvMAGIC(itervar);
      |         ^~~~~
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4374:9: error: C++ style comments are not allowed in ISO C90
 4374 |         // LV ref around a package lexical, mg_obj gives its GV
      |         ^
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4374:9: note: (this will be reported only once per input file)
...
```

**Comment by mauke** [comment]
Related: https://github.com/Perl/perl5/issues/24018
