### PR TITLE
don't force C89 ("ANSI") mode

### LINKED ISSUE #298: Does not compile on perl 5.44
See https://www.cpantesters.org/cpan/report/f00f68cc-721a-11f1-8685-c5e7b9a02d72.

```
...
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h: In function ‘Perl_cx_poploop’:
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4352:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 4352 |         PADOFFSET how_many = iterop->op_targ;
      |         ^~~~~~~~~
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4357:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
 4357 |         for (SV **svp = cx->blk_loop.itervar_u.svp + 1; how_many; svp++, how_many--) {
      |         ^~~
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4357:9: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4370:9: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 4370 |         MAGIC *mg = SvMAGIC(itervar);
      |         ^~~~~
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4374:9: error: C++ style comments are not allowed in ISO C90
 4374 |         // LV ref around a package lexical, mg_obj gives its GV
      |         ^
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4374:9: note: (this will be reported only once per input file)
...
```

### PR DESCRIPTION
**Pull request by mauke**
Perl has been using some C99 features since 5.36.0: https://perldoc.perl.org/perl5360delta#Configuration-and-Compilation

Starting with 5.44.0, `//` comments and for-loop declarations have started appearing in `inline.h`. This is incompatible with C89, so don't force `-ansi` in Build.PL.

Fixes #298.

### CODE REVIEW

**Comment by jeffreykegler** [comment]
Thanks.  These will force a conversation about who takes over this project -- I am 72 and not in perfect health.  But what is, is. :-)

**Comment by jkeenan** [comment]
> Thanks. These will force a conversation about who takes over this project -- I am 72 and not in perfect health. But what is, is. :-)

Do you anticipate being able to do a new CPAN release anytime soon?  Thanks.

**Comment by jeffreykegler** [comment]
Yes, a new release is my highest priority, after personal matters. So it is taking place right now, albeit slowly.

Sent from [Proton Mail](https://proton.me/mail/home) for Android.

-------- Original Message --------

**Comment by jeffreykegler** [comment]
Fixed in developer's release https://pause.perl.org/pub/PAUSE/authors/id/J/JK/JKEGL/Marpa-R2-11.003_000.tar.gz -- this is a release candidate.  An official release will follow in the next week or two.

**Comment by jkeenan** [comment]
> Fixed in developer's release https://pause.perl.org/pub/PAUSE/authors/id/J/JK/JKEGL/Marpa-R2-11.003_000.tar.gz -- this is a release candidate. An official release will follow in the next week or two.

Thank you for your rapid response.  I look forward to the new CPAN release.

**Comment by jeffreykegler** [comment]
This issue is fixed in the official release, Marpa::R2 14.000000, which is now out.
